apiVersion: v1
kind: Service
metadata:
  name: backend-merge
spec:
  selector:
    app: backend-merger
  ports:
  - port: 8080
    targetPort: backend-port
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: backend-rotate
spec:
  selector:
    app: backend-rotate
  ports:
  - port: 8081
    targetPort: rotate-port
    protocol: TCP
