# Get more info on the settings.yaml here:https://github.com/apps/settings
repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: PDF-Editor

  # A short description of the repository that will show up on GitHub
  description: PDF Editor

  # A URL with more information about the repository
  # homepage: %^%$

  # Collaborators: give specific users access to this repository.
  # see /governance/roles.md for details on write access policy
  # note that the permissions below may provide wider access than needed for
  # a specific role, and we trust these individuals to act according to their
  # role. If there are questions, please contact one of the chairs.
collaborators:
  # Chairs
  - username: dipankardas011
    permission: admin

  - username: umgbhalla
    permission: maintain

branches:

  # Default branch of this repository for configurations and English contents
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
      required_status_checks: null
      restrictions:
        apps: []
        # En approvers (including Chairs)
        users:
         - dipankardas011
         - umgbhalla
        teams: []
      enforce_admins: null
      required_linear_history: null

