version: '3'
services:
  backend:
    image: docker.io/dipugodocker/pdf-editor:backend
    container_name: backend
    ports:
      - "8080"
    networks:
      - pdf-editor
    volumes:
      - db_data:/app/

  frontend:
    depends_on:
      - backend
    image: docker.io/dipugodocker/pdf-editor:frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - pdf-editor
  trace:
    depends_on:
      - backend
      - frontend
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "16686:16686"
      - "6831:6831"
    networks:
      - pdf-editor

networks:
  pdf-editor:

volumes:
  db_data:
# You need to change the index.html where it has HTTP call to the backend =>> http://localhost:10001/....
