version: '3'

volumes:
  app_data_M:
  app_data_R:

networks:
  pdf-editor:
services:
  backend-merge:
    image: docker.io/dipugodocker/pdf-editor:1.0-backend-merge
    container_name: backend-merge
    ports:
      - "8080"
    networks:
      - pdf-editor
    volumes:
      - app_data_M:/go/src

  backend-rotate:
    image: docker.io/dipugodocker/pdf-editor:1.0-backend-rotate
    container_name: backend-rotate
    ports:
      - "8081"
    volumes:
      - app_data_R:/go/src
    networks:
      - pdf-editor

  frontend:
    depends_on:
      - backend-merge
      - backend-rotate
    image: docker.io/dipugodocker/pdf-editor:1.0-frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - pdf-editor

  trace:
    depends_on:
      - frontend
    image: jaegertracing/all-in-one
    container_name: jaeger-tracing-pdf
    ports:
    - "6831"
    - "6832"
    - "5778"
    - "16686:16686"
    - "4317"
    - "4318"
    - "14250"
    - "14268"
    - "14269"
    - "9411"
    networks:
      - pdf-editor
