version: 'beta'
services:
  app:
    image: dipugodocker/pdf-editor:beta
    ports:
      - "9090:5000"
    environment:
      - PORT=5000
    networks:
      - back-tier
      
  db:
    depends_on:
      - db_web
    image: redis
    command: 
    - sh
    - -c
    - "redis-server ; redis-cli --quoted-input set name dipankar"
    - "sleep 100"
    - "rm /website/*"
    - "redis-cli --quoted-input get name > /website/index.html"
    networks:
      - back-tier
    volumes:
      - db_data:/website/
  
  db_web:
    image: nginx:alpine
    ports:
      - "9091:80"
    volumes:
      - db_data:/usr/share/nginx/html

networks:
  back-tier:

volumes:
  db_data:

# access one from another
# inside app then db:6379 and viceversa app:5000