apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-editor-backend-merge
  namespace: {{ .Values.namespace }}
  labels:
    web: pdf-editor-merge
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      web: pdf-editor-merge
  template:
    metadata:
      labels:
        web: pdf-editor-merge

    spec:
      volumes:
      - name: backend
        emptyDir: {}
      initContainers:
        - name: pdf-files
          image: docker.io/dipugodocker/pdf-editor:{{ .Chart.AppVersion }}-backend-merge
          volumeMounts:
          - name: backend
            mountPath: /mnt
          command: ["cp", "-vR", ".", "/mnt"]

      containers:
        - name: pdf-editor
          image: docker.io/dipugodocker/pdf-editor:{{ .Chart.AppVersion }}-backend-merge
          volumeMounts:
          - name: backend
            mountPath: /go/src/
          resources:
            requests:
                memory: "50Mi"
                cpu: "10m"
            limits:
              memory: "500Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              port: 8080
              path: /greet
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              port: 8080
              path: /greet
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8080
          imagePullPolicy: {{ .Values.image.pullPolicy }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-editor-backend-rotate
  namespace: {{ .Values.namespace }}
  labels:
    web: pdf-editor-rotate
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      web: pdf-editor-rotate
  template:
    metadata:
      labels:
        web: pdf-editor-rotate

    spec:
      volumes:
      - name: backend
        emptyDir: {}
      initContainers:
        - name: pdf-files
          image: docker.io/dipugodocker/pdf-editor:0.1-backend-rotate
          volumeMounts:
          - name: backend
            mountPath: /mnt
          command: ["cp", "-vR", ".", "/mnt"]

      containers:
        - name: pdf-editor
          image: docker.io/dipugodocker/pdf-editor:0.1-backend-rotate
          volumeMounts:
          - name: backend
            mountPath: /go/src/
          resources:
            requests:
                memory: "50Mi"
                cpu: "10m"
            limits:
              memory: "500Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              port: 8081
              path: /greet
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              port: 8081
              path: /greet
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8081
          imagePullPolicy: {{ .Values.image.pullPolicy }}



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-editor-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend-pdf
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: frontend-pdf
  template:
    metadata:
      labels:
        app: frontend-pdf
    spec:
      containers:
        - name: pdf-editor
          image: docker.io/dipugodocker/pdf-editor:{{ .Chart.AppVersion }}-frontend
          resources:
            requests:
                memory: "50Mi"
                cpu: "10m"
            limits:
              memory: "500Mi"
              cpu: "100m"
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 80
              name: web-port
          imagePullPolicy: {{ .Values.image.pullPolicy }}
...
