version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - run:
          name: Simple debug
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: check go version
          command: |
            go version
