version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Unit-Testing backend-merger
          command: |
            cd src/backend/merger
            docker build --target test -t xyz .
            docker run --rm xyz

      - run:
          name: Unit-Testing frontend
          command: |
            cd src/frontend
            docker build --target test -t xyz .
            docker run --rm xyz

      - run:
          name: Integration-Testing Merger
          command: |
            cd test/integration
            export PORT=9090
            chmod +x test-merger.sh
            ./test-merger.sh