version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Simple debug
          command: |
            echo 'testing go'

      - run:
          name: Testing backend
          command: |
            cd src/backend/merger
            docker build --target test -t xyz .
            docker run --rm xyz

      - run:
          name: Testing frontend
          command: |
            cd src/frontend
            docker build --target test -t xyz .
            docker run --rm xyz
