version: '3'
services:
  backend-merge:
    depends_on:
      - backend-db
    image: docker.io/dipugodocker/pdf-editor:backend-merge
    container_name: backend-merger
    ports:
      - "8080"
    networks:
      - pdf-editor
    volumes:
      - app_data:/go/src

  backend-rotate:
    depends_on:
      - backend-db
    image: docker.io/dipugodocker/pdf-editor:backend-rotate
    container_name: backend-rotator
    ports:
      - "8081"
    networks:
      - pdf-editor

  backend-db:
    image: docker.io/dipugodocker/pdf-editor:backend-db
    container_name: backend-database
    ports:
      - "6379"
    networks:
      - pdf-editor
    volumes:
      - db_data:/data

  frontend:
    depends_on:
      - backend-merge
      - backend-rotate
    image: docker.io/dipugodocker/pdf-editor:frontend
    container_name: frontend-merger-pdf
    ports:
      - "80:80"
    networks:
      - pdf-editor

  trace:
    depends_on:
      - backend
      - frontend
    image: jaegertracing/all-in-one
    container_name: jaeger-tracing-pdf
    ports:
    - "6831"
    - "6832"
    - "5778"
    - "16686:16686"
    - "4317"
    - "4318"
    - "14250"
    - "14268"
    - "14269"
    - "9411"
    networks:
      - pdf-editor

networks:
  pdf-editor:

volumes:
  db_data:
  app_data:
