apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-editor-web
  labels:
    web: pdf-editor
  namespace: pdf-editor
spec:
  replicas: 5
  selector:
    matchLabels:
      web: pdf-editor
  template:
    metadata:
      labels:
        web: pdf-editor

    spec:
      containers:
        - name: pdf-editor
          image: dipugodocker/pdf-editor:0.5v@sha256:f854d0e98f486466ef808f2e42e15a2cd1db942c270a6a70c2c911c2599a9b25
          env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: pdf-config
                key: PORT
          resources:
            requests:
                memory: "50Mi"
                cpu: "100m"
            limits:
              memory: "400Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 5680 # as we are not specifiing the $PORT so default is 8080
          ports:
            - containerPort: 5680
          imagePullPolicy: Always
...
