apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-editor-web
  labels:
    web: pdf-editor
spec:
  replicas: 2
  selector:
    matchLabels:
      web: pdf-editor
  template:
    metadata:
      labels:
        web: pdf-editor

    spec:
      containers:
        - name: PDF-editor
          image: dipugodocker/pdf-editor:0.1v
          resources:
            requests:
                memory: "50Mi"
                cpu: "100m"
            limits:
              memory: "400Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          ports:
            - containerPort: 8080
...