# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pdf-editor-pvc
#   labels:
#     pvc: pdf
#   namespace: pdf-editor-ns
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: standard
#   resources:
#     requests:
#       storage: 50Mi