apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: backend-rotate-cilium-policy
  namespace: pdf-editor-ns
spec:
  endpointSelector:
    matchLabels:
      service: backend-rotate
  ingress:
    - fromEndpoints:
        - matchLabels:
            name: pdf-editor-frontend
      toPorts:
        - ports:
            - port: "8081"
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toServices:
        - k8sServiceSelector:
            selector:
              matchLabels:
                name: pdf-editor-frontend

