apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-editor-web
  namespace: {{ .Values.namespace.dev }}
  labels:
    web: pdf-editor
spec:
  replicas: {{ .Values.replicaCount.dev }}
  selector:
    matchLabels:
      web: pdf-editor
  template:
    metadata:
      labels:
        web: pdf-editor

    spec:
      containers:
        - name: pdf-editor
          image: {{ .Values.image.repository }}{{ .Values.image.tag }}
          env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: pdf-config
                key: PORT
          resources:
            requests:
                memory: "50Mi"
                cpu: "100m"
            limits:
              memory: "400Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 5680 # as we are not specifiing the $PORT so default is 8080
          ports:
            - containerPort: 5680
          imagePullPolicy: {{ .Values.image.pullPolicy }}
...