apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pdf-editor-backend
  namespace: argocd
spec:
  project: pdf-editor
  source:
    repoURL: 'https://github.com/dipankardas011/PDF-Editor/'
    path: deploy/cluster/backend
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pdf-editor-ns
  syncPolicy:
    syncOptions:
      - CreateNamespace=true      # to create the namaspace if not exsists
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pdf-editor-frontend
  namespace: argocd
spec:
  project: pdf-editor
  source:
    repoURL: 'https://github.com/dipankardas011/PDF-Editor/'
    path: deploy/cluster/frontend
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pdf-editor-ns
  syncPolicy:
    syncOptions:
      - CreateNamespace=true      # to create the namaspace if not exsists
    automated:
      prune: true
      selfHeal: true