name: '[Stable](Backend-merger) Docker Signed Image Release'

on:
  schedule:
    # Monthly release at 12'o clock
    - cron: "0 12 1 * *"
  workflow_dispatch:
    inputs:
      version:
        description: Version(Optional)
        default: v1.0.0
        required: false
jobs:
  docker-push-backend-merge-Sign-using-cosign:
    runs-on: ubuntu-latest
    environment: deploy

    env:
      SUPER_SECRET: ${{ secrets.DOCKER_PASS }}
      BACKEND_MERGE: dipugodocker/pdf-editor:1.0-backend-merge

    name: Install Cosign and test presence in path
    steps:
      - uses: actions/checkout@v3


      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        # with:
        #   cosign-release: main
      - name: Check Version
        run: |
          cosign version
          docker login -u dipugodocker -p "$SUPER_SECRET"

      - name: build all 🏭 Images
        run: |
          echo '[🏭] Building for Production [Backend-merger]'
          cd src/backend/merger && docker build --target prod -t $BACKEND_MERGE . --no-cache

      - name: push all
        run: |
          docker push $BACKEND_MERGE

      - name: sign
        run: |
          echo -n "${{secrets.COSIGNPASSWORD}}" | cosign sign --key cosign.key -a git_sha=$GITHUB_SHA $BACKEND_MERGE

      - name: verify
        run: |
          cosign verify --key cosign.pub -a git_sha=$GITHUB_SHA $BACKEND_MERGE | jq .

  helm-artifact-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: package
        run: |-
          cd deploy/cluster
          helm package pdf-editor-helm
          mv pdf-editor-helm-1.0.0.tgz artifact/
          helm repo index artifact
