name: '[Stable](Frontend) Stable Docker Signed Image Release'

on:
  schedule:
    # Monthly release at 12'o clock
    - cron: "0 12 1 * *"
  workflow_dispatch:
    inputs:
      version:
        description: Version(Optional)
        default: v1.0.0
        required: false
jobs:
  docker-push-frontend-Sign-using-cosign:
    runs-on: ubuntu-latest
    environment: deploy

    env:
      SUPER_SECRET: ${{ secrets.DOCKER_PASS }}
      FRONTEND: dipugodocker/pdf-editor:1.0-frontend

    name: Install Cosign and test presence in path
    steps:
      - uses: actions/checkout@v3


      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        # with:
        #   cosign-release: main
      - name: Check Version
        run: |
          cosign version
          docker login -u dipugodocker -p "$SUPER_SECRET"

      - name: Build 🏭 Frontend Images
        run: |
          echo '[🏭] Building Prod [Frontend]'
          cd src/frontend && docker build --target prod -t $FRONTEND . --no-cache

      - name: push Frontend
        run: |
          docker push $FRONTEND

      - name: sign
        run: |
          echo -n "${{secrets.COSIGNPASSWORD}}" | cosign sign --key cosign.key -a git_sha=$GITHUB_SHA $FRONTEND

      - name: verify
        run: |
          cosign verify --key cosign.pub -a git_sha=$GITHUB_SHA $FRONTEND | jq .

  helm-artifact-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: package
        run: |-
          cd deploy/cluster
          helm package pdf-editor-helm
          mv pdf-editor-helm-1.0.0.tgz artifact/
          helm repo index artifact
