---
name: K8s Manifest Sec checks Kubescape

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  kubescape:

    runs-on: ubuntu-latest
    environment: testing

    steps:
    - uses: actions/checkout@v3
    
    - name: 🧪 Install Kubescape
      run: 'curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash'
    
    - name: 🧪 Kubescape version
      run: kubescape version
    
    - name: Check the backend
      run: |
        cd deploy/cluster/
        kubescape scan -v backend/*.yml
    
    - name: Check the frontend
      run: |
        cd deploy/cluster/
        kubescape scan -v frontend/*.yml
...
