name: PR Checks 🤞🏼

on:
  pull_request:
    branches: [ main ]
jobs:
  golang_build:

    runs-on: ubuntu-latest
    environment: testing

    steps:
    - uses: actions/checkout@v3
    - name: 🧪 backend Merger
      run: |
        cd src/backend/merger
        docker build --target test -t xyz .
        docker run --rm xyz
    - name: 🧪 backend Rotator
      run: |
        cd src/backend/rotator
        docker build --target test -t xyz .
        docker run --rm xyz

  npm_build:

    runs-on: ubuntu-latest
    environment: testing

    steps:
    - uses: actions/checkout@v3
    - name: 🧪 frontend
      run: |
        cd src/frontend
        docker build --target test -t xyz .
        docker run --rm xyz

  docker_build:

    needs: [golang_build,npm_build]

    runs-on: ubuntu-latest
    environment: testing

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd src/backend/merger
        docker build . --target prod --file Dockerfile --tag pdf-editor:$(date +%s)-merge
        cd ../rotator
        docker build . --target prod --file Dockerfile --tag pdf-editor:$(date +%s)-rotate
        cd ../../frontend
        docker build . --target prod --file Dockerfile --tag pdf-editor:$(date +%s)-frontend
