name: PR Checks 🤞🏼

on:
  pull_request:
    branches: [ main ]
jobs:
  golang_build:

    runs-on: ubuntu-latest
    environment: testing

    steps:
    - uses: actions/checkout@v3
    - name: 🧪 backend Merger
      run: |
        cd src/backend/merger
        docker build --target test -t xyz .
        docker run --rm xyz

  npm_build:

    runs-on: ubuntu-latest
    environment: testing

    steps:
    - uses: actions/checkout@v3
    - name: 🧪 frontend
      run: |
        cd src/frontend
        docker build --target test -t xyz .
        docker run --rm xyz

  docker_build:

    needs: [golang_build,npm_build]

    runs-on: ubuntu-latest
    environment: testing

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd src/backend/merger
        docker build . --target prod --file Dockerfile --tag pdf-editor:$(date +%s)-merge
        cd ../rotator
        docker build . --target prod --file Dockerfile --tag pdf-editor:$(date +%s)-rotate
        cd ../db
        docker build . --target db-prod --file Dockerfile --tag pdf-editor:$(date +%s)-db
        cd ../../frontend
        docker build . --target prod --file Dockerfile --tag pdf-editor:$(date +%s)-frontend

  # heroku-preview:
  #   needs: [docker_build]
  #   runs-on: ubuntu-latest
  #   environment: preview
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Login to Heroku Container registry
  #     env:
  #       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #     run: heroku container:login
  #   - name: Build and push
  #     env:
  #       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #     run: |
  #       cd backEnd/
  #       heroku container:push -a ${{ secrets.HEROKU_APP_NAME_PR }} web
  #   - name: Release
  #     env:
  #       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #     run: |
  #       cd backEnd/
  #       heroku container:release -a ${{ secrets.HEROKU_APP_NAME_PR }} web

  # preview:
  #   needs: [heroku-preview, docker_build, golang_build]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Comment Checkout
  #     uses: NejcZdovc/comment-pr@v1
  #     with:
  #       message: |
  #         # Preview for the App
  #         📱🚀🥳
  #         Provider | Status | Link
  #         -|-|-
  #         ![Heroku](https://img.shields.io/badge/heroku-%23430098.svg?style=for-the-badge&logo=heroku&logoColor=white) | ✅ | https://pdf-web.herokuapp.com/
  #     env:
  #       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

