name: CI Checks 🤞🏼

on:
  pull_request:
    branches: [ main ]
jobs:
  golang_build:

    runs-on: ubuntu-latest
    environment: testing

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: |
        cd src/backend
        go build -v ./...

    - name: Test
      run: |
        cd src/backend
        go test -v ./...

  docker_build:

    needs: [golang_build]

    runs-on: ubuntu-latest
    environment: testing

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd src/backend
        docker build . --file Dockerfile --tag pdf-editor:$(date +%s)
        cd ../frontend
        docker build . --file Dockerfile --tag pdf-editor:$(date +%s)

  test_cosign_action:
    runs-on: ubuntu-latest

    permissions: {}

    name: Install Cosign and test presence in path
    steps:
      - uses: actions/checkout@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        # with:
        #   cosign-release: main
      - name: Check install!
        run: cosign version

      - name: build
        run: |
          cd src/backend
          docker build . -t docker.io/dipugodocker/pdf-editor:backend-$GITHUB_SHA

      - name: sign
        run: echo -n "${{secrets.COSIGNPASSWORD}}" | cosign sign --key cosign.key -a git_sha=$GITHUB_SHA docker.io/dipugodocker/pdf-editor:backend-$GITHUB_SHA

      - name: verify
        run: cosign verify --key cosign.pub -a git_sha=$GITHUB_SHA docker.io/dipugodocker/pdf-editor:backend-$GITHUB_SHA
  # heroku-preview:
  #   needs: [docker_build]
  #   runs-on: ubuntu-latest
  #   environment: preview
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Login to Heroku Container registry
  #     env:
  #       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #     run: heroku container:login
  #   - name: Build and push
  #     env:
  #       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #     run: |
  #       cd backEnd/
  #       heroku container:push -a ${{ secrets.HEROKU_APP_NAME_PR }} web
  #   - name: Release
  #     env:
  #       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #     run: |
  #       cd backEnd/
  #       heroku container:release -a ${{ secrets.HEROKU_APP_NAME_PR }} web

  # preview:
  #   needs: [heroku-preview, docker_build, golang_build]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Comment Checkout
  #     uses: NejcZdovc/comment-pr@v1
  #     with:
  #       message: |
  #         # Preview for the App
  #         📱🚀🥳
  #         Provider | Status | Link
  #         -|-|-
  #         ![Heroku](https://img.shields.io/badge/heroku-%23430098.svg?style=for-the-badge&logo=heroku&logoColor=white) | ✅ | https://pdf-web.herokuapp.com/
  #     env:
  #       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

