name: ImageScan [Aqua Trivy]

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  scanDockerImages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd backEnd/
        port=8080
        docker build . --tag imagescan
        docker run aquasec/trivy image imagescan